# Generated by Django 6.1.1 on 2026-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('imei', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
